const USER_COLLECTION_NAME = "users"
const POSITION_COLLECTION_NAME = "positions"
const POST_COLLECTION_NAME = "posts"

export {
  USER_COLLECTION_NAME,
  POSITION_COLLECTION_NAME,
  POST_COLLECTION_NAME
}